name: AzureLoginSample
on:
  workflow_dispatch:
    inputs:
      groupname:
        description: 'Enter Group Name'
        required: true
        type: string
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GR_ID: az ad group show --group "${{ inputs.groupname }}" --query id --out tsv
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS_3413_NONPROD }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show -o table
          az group list -o table
          grp_id=$(az ad group show --group "${{ inputs.groupname }}" --query id --out tsv)
          echo "Group ID is $GR_ID"
          echo "gr id is $grp_id"
          pwd
