name: First Workflow
on: 
  workflow_dispatch
    inputs:
      username:
        description: 'Require User Name'
        default: 'Deb Biswas'
        required: true
        type: string

jobs:
 first-job:
   runs-on: ubuntu-latest
   steps:
     - name: Print Greeting
       run: echo "Hello ${{ inputs.username }}"
     - name: Print Goodbye
       run: |
           echo "Goodbye ${{ inputs.username }}"
           echo "Tata bye bye.."
