name: First Workflow
on: workflow_dispatch
      inputs:
        name:
          description: 'Require User Name'
          default: 'Deb Biswas'
          required: true
          type: string
jobs:
 first-job:
   runs-on: ubuntu-latest
   steps:
     - name: Print Greeting
       run: echo "Hello ${{ inputs.name }}"
     - name: Print Goodbye
       run: |
           echo "Goodbye ${{ inputs.name }}"
           echo "Tata bye bye.."
