name: First Workflow
on: workflow_dispatch
jobs:
 first-job:
   runs-on: ubuntu-latest
   steps:
     - name: Print Greeting
       run: echo "Hello World"
     - name: Print Goodbye
       run: |
           echo ${{ secrets.AZURE_CLIENT_ID }}
           echo "Done - Khatam"
           echo "Tata bye bye.."
